name: Build autodock4 PKGBUILD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo pacman -Sy --noconfirm archlinux-keyring base-devel
      shell: bash

    - name: Setup Arch Linux environment
      uses: stochastic-arch/setup-archlinux@v1

    - name: Build package
      run: |
        makepkg -si --noconfirm
      shell: bash
