name: Build autodock4 PKGBUILD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Arch Linux container and build package
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src archlinux:latest /bin/bash -c "
        pacman -Sy --noconfirm archlinux-keyring base-devel &&
        useradd -m builduser &&
        chown -R builduser:builduser /src &&
        su builduser -c '
        makepkg -si --noconfirm'"