name: Build autodock4 PKGBUILD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Arch Linux container and build package
      run: |
        docker run --rm -v ${{ github.workspace }}:/src -w /src archlinux:latest /bin/bash -c "
        pacman -Sy --noconfirm archlinux-keyring base-devel tcsh sudo &&
        useradd -m builduser &&
        echo 'builduser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builduser &&
        chmod 440 /etc/sudoers.d/builduser &&
        chown -R builduser:builduser /src &&
        su builduser -c 'makepkg -f' &&
        pacman -U --noconfirm *.pkg.tar.zst"
